services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # target: app
    image: ghcr.io/sunmh207/ai-codereview-gitlab:1.4.0.1
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./data:/app/data
      - ./log:/app/log
    env_file:
      - ./conf/.env
    restart: unless-stopped